<?php

namespace App\Notifications;

use App\Models\Agreement;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Aviso de que un cliente firmó un formulario (Agreement) — se envía al
 * grupo configurado en NotificationRule (evento agreement_signed), ya que
 * hoy nadie se entera automáticamente cuando esto pasa. El texto va siempre
 * en inglés, igual que TicketEventNotification.
 */
class AgreementSignedNotification extends Notification
{
    use Queueable;

    public function __construct(public Agreement $agreement, public ?string $trackingToken = null) {}

    /**
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $agreement = $this->agreement;

        $details = [
            'Account' => $agreement->account_id,
            'Business Name' => $agreement->business_name,
            "Owner's Name" => $agreement->owner_name,
            'Phone' => $agreement->phone,
            'Address' => $agreement->address,
            'Signed' => $agreement->signed_at->format('m/d/Y H:i'),
        ];

        if ($agreement->total_amount) {
            $details['Total amount'] = '$'.number_format((float) $agreement->total_amount, 2);
        }

        return (new MailMessage)
            ->subject($this->subject())
            ->view('emails.branded', [
                'intro' => $this->line(),
                'details' => $details,
                'note' => $agreement->creator ? "Link generated by {$agreement->creator->name}." : null,
                'ctaLabel' => 'View form',
                'ctaUrl' => route('admin.agreements.show', $agreement),
                'signatureName' => null,
                'signatureRole' => null,
                'trackingUrl' => $this->trackingToken ? route('email.tracking', $this->trackingToken) : null,
            ]);
    }

    /**
     * @return array<string, mixed>
     */
    public function toDatabase(object $notifiable): array
    {
        return [
            'agreement_id' => $this->agreement->id,
            'subject' => $this->subject(),
            'line' => $this->line(),
            'url' => route('admin.agreements.show', $this->agreement),
        ];
    }

    public function subject(): string
    {
        return "Form signed: {$this->agreement->account_id}";
    }

    protected function line(): string
    {
        return "{$this->agreement->owner_name} just signed the form for account {$this->agreement->account_id}.";
    }
}
