<?php

namespace App\Notifications;

use App\Models\Agreement;
use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

/**
 * Aviso de que un cliente firmó un formulario (Agreement) — se envía al
 * grupo configurado en NotificationRule (evento agreement_signed), ya que
 * hoy nadie se entera automáticamente cuando esto pasa.
 */
class AgreementSignedNotification extends Notification
{
    use Queueable;

    public function __construct(public Agreement $agreement) {}

    /**
     * @return array<int, string>
     */
    public function via(object $notifiable): array
    {
        return ['mail', 'database'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $agreement = $this->agreement;

        $details = [
            __('Account') => $agreement->account_id,
            __('Business Name') => $agreement->business_name,
            __("Owner's Name") => $agreement->owner_name,
            __('Phone') => $agreement->phone,
            __('Address') => $agreement->address,
            __('Signed :date', ['date' => $agreement->signed_at->format('d/m/Y H:i')]) => $agreement->signed_at->format('d/m/Y H:i'),
        ];

        if ($agreement->total_amount) {
            $details[__('TOTAL AMOUNT')] = '$'.number_format((float) $agreement->total_amount, 2);
        }

        return (new MailMessage)
            ->subject(__('Form signed: :account', ['account' => $agreement->account_id]))
            ->view('emails.branded', [
                'intro' => __(':owner just signed the form for account :account.', [
                    'owner' => $agreement->owner_name,
                    'account' => $agreement->account_id,
                ]),
                'details' => $details,
                'note' => $agreement->creator ? __('Link generated by :name.', ['name' => $agreement->creator->name]) : null,
                'ctaLabel' => __('View form'),
                'ctaUrl' => route('admin.agreements.show', $agreement),
                'signatureName' => null,
                'signatureRole' => null,
            ]);
    }

    /**
     * @return array<string, mixed>
     */
    public function toDatabase(object $notifiable): array
    {
        return [
            'agreement_id' => $this->agreement->id,
            'subject' => __('Form signed: :account', ['account' => $this->agreement->account_id]),
            'line' => __(':owner just signed the form for account :account.', [
                'owner' => $this->agreement->owner_name,
                'account' => $this->agreement->account_id,
            ]),
            'url' => route('admin.agreements.show', $this->agreement),
        ];
    }
}
